package contacts_test

// vCard 4.0 converter tests (REQ-CTS-10..14, REQ-CTS-40).
//
// TestVCard_RoundTrip_* tests assert REQ-CTS-13 (round-trip equivalence)
// for the representative fixture cards listed in the requirement.
//
// Comparison is semantic rather than byte-equal: map keys generated by
// ParseVCards are deterministic ("email/0", "phone/0", …) but differ
// from keys a client might supply; we compare the value sets.

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/hanshuebner/herold/internal/protojmap/contacts"
)

// ===== ParseVCards =====

func TestVCard_ParseMinimal(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Alice\r\nUID:urn:uuid:1\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 {
		t.Fatalf("want 1 result, got %d", len(results))
	}
	if results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	c := results[0].Card
	if c.UID != "urn:uuid:1" {
		t.Errorf("UID = %q, want urn:uuid:1", c.UID)
	}
	if c.Name == nil || c.Name.Full != "Alice" {
		name := "<nil>"
		if c.Name != nil {
			name = c.Name.Full
		}
		t.Errorf("Name.Full = %q, want Alice", name)
	}
	if c.Version != "1.0" {
		t.Errorf("Version = %q, want 1.0", c.Version)
	}
}

func TestVCard_ParseFull(t *testing.T) {
	vcf := strings.Join([]string{
		"BEGIN:VCARD",
		"VERSION:4.0",
		"UID:urn:uuid:full-1",
		"KIND:individual",
		"FN:Ada Lovelace",
		"N:Lovelace;Ada;Augusta;Hon.;",
		"EMAIL;TYPE=work;PREF=1:ada@example.test",
		"EMAIL;TYPE=home:ada-personal@example.test",
		"TEL;TYPE=voice,work;PREF=1:+44 20 7946 0958",
		"TEL;TYPE=cell:+44 7700 900123",
		"ADR;TYPE=work;CC=GB:;;10 Downing Street;London;;SW1A 2AA;United Kingdom",
		"ORG:Analytical Engine Co.;Research",
		"TITLE:Mathematician",
		"ROLE:Fellow",
		`NICKNAME:Ada\,Countess`,
		"NOTE:Pioneer of computing.",
		"URL;PREF=1:https://lovelace.example.test",
		"BDAY:18151210",
		"ANNIVERSARY:--1225",
		"END:VCARD",
	}, "\r\n") + "\r\n"

	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 {
		t.Fatalf("want 1 result, got %d", len(results))
	}
	if results[0].Error != nil {
		t.Fatalf("parse error: %v", results[0].Error)
	}
	c := results[0].Card

	if c.Kind != "individual" {
		t.Errorf("Kind = %q, want individual", c.Kind)
	}
	if c.Name == nil {
		t.Fatal("Name is nil")
	}
	if c.Name.Full != "Ada Lovelace" {
		t.Errorf("Name.Full = %q, want Ada Lovelace", c.Name.Full)
	}
	assertNameComponent(t, c, "surname", "Lovelace")
	assertNameComponent(t, c, "given", "Ada")
	assertNameComponent(t, c, "middle", "Augusta")
	assertNameComponent(t, c, "prefix", "Hon.")

	if len(c.Emails) != 2 {
		t.Errorf("Emails count = %d, want 2", len(c.Emails))
	}
	assertEmailExists(t, c, "ada@example.test", true)
	assertEmailExists(t, c, "ada-personal@example.test", false)
	assertPrimaryEmail(t, c, "ada@example.test")

	if len(c.Phones) != 2 {
		t.Errorf("Phones count = %d, want 2", len(c.Phones))
	}
	assertPhoneFeature(t, c, "+44 20 7946 0958", "voice")
	assertPhoneFeature(t, c, "+44 7700 900123", "cell")

	if len(c.Addresses) != 1 {
		t.Errorf("Addresses count = %d, want 1", len(c.Addresses))
	}
	for _, a := range c.Addresses {
		if a.CountryCode != "GB" {
			t.Errorf("CountryCode = %q, want GB", a.CountryCode)
		}
		assertAddrComponent(t, a, "city", "London")
		assertAddrComponent(t, a, "postcode", "SW1A 2AA")
	}

	if len(c.Organizations) != 1 {
		t.Errorf("Orgs count = %d, want 1", len(c.Organizations))
	}
	for _, o := range c.Organizations {
		if o.Name != "Analytical Engine Co." {
			t.Errorf("Org.Name = %q", o.Name)
		}
		if len(o.Units) != 1 || o.Units[0] != "Research" {
			t.Errorf("Org.Units = %v, want [Research]", o.Units)
		}
	}

	if len(c.Titles) != 2 {
		t.Errorf("Titles count = %d, want 2", len(c.Titles))
	}
	assertTitleKind(t, c, "Mathematician", "title")
	assertTitleKind(t, c, "Fellow", "role")

	assertRawJSONHasNickname(t, c, "Ada,Countess")
	assertRawJSONHasNote(t, c, "Pioneer of computing.")
	assertRawJSONHasURL(t, c, "https://lovelace.example.test")
	assertRawJSONHasBirthday(t, c, 1815, 12, 10)
	assertRawJSONHasAnniversary(t, c, 0, 12, 25)
}

func TestVCard_ParseMultiple(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Alice\r\nUID:urn:uuid:a\r\nEND:VCARD\r\n" +
		"BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Bob\r\nUID:urn:uuid:b\r\nEND:VCARD\r\n"

	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 2 {
		t.Fatalf("want 2 results, got %d", len(results))
	}
	for i, r := range results {
		if r.Error != nil {
			t.Errorf("result[%d] error: %v", i, r.Error)
		}
	}
	names := map[string]bool{
		results[0].Card.Name.Full: true,
		results[1].Card.Name.Full: true,
	}
	if !names["Alice"] || !names["Bob"] {
		t.Errorf("names = %v, want Alice and Bob", names)
	}
}

func TestVCard_ParseMalformed_Truncated(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Partial" // no END:VCARD
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 {
		t.Fatalf("want 1 result, got %d", len(results))
	}
	if results[0].Error == nil {
		t.Error("want error for truncated card, got nil")
	}
	if results[0].Card != nil {
		t.Error("want nil card on error")
	}
}

func TestVCard_ParseMalformed_OneBadOneGood(t *testing.T) {
	good := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Good\r\nUID:urn:uuid:g\r\nEND:VCARD\r\n"
	// A card whose property line has no value separator is malformed.
	bad := "BEGIN:VCARD\r\nVERSION:4.0\r\nNOSEPARATOR\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(good+bad), nil)
	if len(results) != 2 {
		t.Fatalf("want 2 results, got %d", len(results))
	}
	if results[0].Error != nil {
		t.Errorf("good card: unexpected error: %v", results[0].Error)
	}
	// Bad card: either an error or a parsed card — we just require no panic.
}

func TestVCard_ParseEmpty(t *testing.T) {
	if results := contacts.ParseVCards(nil, nil); len(results) != 0 {
		t.Errorf("nil input: want 0 results, got %d", len(results))
	}
	if results := contacts.ParseVCards([]byte{}, nil); len(results) != 0 {
		t.Errorf("empty input: want 0 results, got %d", len(results))
	}
	if results := contacts.ParseVCards([]byte("no cards here"), nil); len(results) != 0 {
		t.Errorf("no-card input: want 0 results, got %d", len(results))
	}
}

func TestVCard_ParseLineFolding(t *testing.T) {
	long := "Very Long Name That Exceeds Seventy Five Octets When Encoded As UTF-8 Indeed"
	// Manually fold at byte 45.
	part1 := long[:45]
	part2 := long[45:]
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nUID:urn:uuid:fold\r\nFN:" +
		part1 + "\r\n " + part2 + "\r\nEND:VCARD\r\n"

	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", func() error {
			if len(results) > 0 {
				return results[0].Error
			}
			return fmt.Errorf("no results")
		}())
	}
	if got := results[0].Card.Name.Full; got != long {
		t.Errorf("Name.Full after fold = %q, want %q", got, long)
	}
}

func TestVCard_ParseEscaping(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nUID:urn:uuid:esc\r\n" +
		`FN:Smith\, John` + "\r\n" +
		`NOTE:Line1\nLine2` + "\r\n" +
		`NOTE:Back\\slash` + "\r\n" +
		"END:VCARD\r\n"

	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	c := results[0].Card
	if c.Name.Full != "Smith, John" {
		t.Errorf("Name.Full = %q, want Smith, John", c.Name.Full)
	}
	assertRawJSONHasNote(t, c, "Line1\nLine2")
	assertRawJSONHasNote(t, c, `Back\slash`)
}

func TestVCard_ParseNonUTF8(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nUID:urn:uuid:enc\r\nFN:Test\xff\xfe\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) == 0 {
		t.Fatal("want at least 1 result (no panic)")
	}
	// Either a parse error or a card with replacement characters — no panic.
}

func TestVCard_ParseKind_Group(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Team\r\nUID:urn:uuid:g\r\nKIND:group\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	if got := results[0].Card.Kind; got != "group" {
		t.Errorf("Kind = %q, want group", got)
	}
}

func TestVCard_ParseKind_Org_Lenient(t *testing.T) {
	// vCard KIND:org has no JSContact equivalent; parser accepts it and
	// leaves card.Kind empty.
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Corp\r\nUID:urn:uuid:org\r\nKIND:org\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	if got := results[0].Card.Kind; got != "" {
		t.Errorf("Kind = %q for vCard 'org', want empty", got)
	}
}

func TestVCard_ParseXProp(t *testing.T) {
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:X\r\nUID:urn:uuid:x\r\n" +
		"X-CUSTOM:myvalue\r\nEND:VCARD\r\n"
	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	c := results[0].Card
	raw, ok := c.RawJSON["vcard:x-custom"]
	if !ok {
		t.Fatal("X-CUSTOM not in RawJSON under vcard:x-custom")
	}
	var v string
	if err := json.Unmarshal(raw, &v); err != nil || v != "myvalue" {
		t.Errorf("X-CUSTOM RawJSON = %q, want \"myvalue\"", string(raw))
	}
}

func TestVCard_ParsePhoto_DataURI(t *testing.T) {
	// Minimal 1×1 PNG as a data URI.
	png1x1 := "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:P\r\nUID:urn:uuid:p\r\n" +
		"PHOTO:" + png1x1 + "\r\nEND:VCARD\r\n"

	results := contacts.ParseVCards([]byte(vcf), nil)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	c := results[0].Card
	medRaw, ok := c.RawJSON["media"]
	if !ok {
		t.Fatal("media not in RawJSON")
	}
	var med map[string]map[string]interface{}
	if err := json.Unmarshal(medRaw, &med); err != nil {
		t.Fatalf("unmarshal media: %v", err)
	}
	var entry map[string]interface{}
	for _, v := range med {
		entry = v
		break
	}
	if entry == nil {
		t.Fatal("no media entry")
	}
	if kind, _ := entry["kind"].(string); kind != "photo" {
		t.Errorf("media kind = %q, want photo", kind)
	}
	uri, _ := entry["uri"].(string)
	if !strings.HasPrefix(uri, "data:image/png") {
		t.Errorf("media uri = %q, want data:image/png prefix", uri)
	}
}

func TestVCard_ParsePhoto_InternFn(t *testing.T) {
	png1x1 := "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
	vcf := "BEGIN:VCARD\r\nVERSION:4.0\r\nFN:P\r\nUID:urn:uuid:p2\r\n" +
		"PHOTO:" + png1x1 + "\r\nEND:VCARD\r\n"

	blobCalled := false
	intern := contacts.PhotoInternFn(func(mediaType string, data []byte) (string, error) {
		blobCalled = true
		if mediaType != "image/png" {
			return "", nil
		}
		return "blob-id-42", nil
	})

	results := contacts.ParseVCards([]byte(vcf), intern)
	if len(results) != 1 || results[0].Error != nil {
		t.Fatalf("unexpected error: %v", results[0].Error)
	}
	if !blobCalled {
		t.Error("PhotoInternFn was not called")
	}
	c := results[0].Card
	var med map[string]map[string]interface{}
	if err := json.Unmarshal(c.RawJSON["media"], &med); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	for _, v := range med {
		if bid, _ := v["blobId"].(string); bid != "blob-id-42" {
			t.Errorf("blobId = %q, want blob-id-42", bid)
		}
	}
}

// ===== GenerateVCard =====

func TestVCard_GenerateMinimal(t *testing.T) {
	c := &contacts.Card{}
	c.Version = "1.0"
	c.UID = "urn:uuid:min"
	c.Kind = "individual"
	c.Name = &contacts.Name{Full: "Minimal"}

	res, err := contacts.GenerateVCard(c, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	vcard := string(res.VCard)
	assertVCardContains(t, vcard, "BEGIN:VCARD")
	assertVCardContains(t, vcard, "VERSION:4.0")
	assertVCardContains(t, vcard, "END:VCARD")
	assertVCardContains(t, vcard, "FN:Minimal")
	assertVCardContains(t, vcard, "UID:urn:uuid:min")
	assertVCardContains(t, vcard, "KIND:individual")
	assertCRLFLineEndings(t, res.VCard)
}

func TestVCard_GenerateFull(t *testing.T) {
	c := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:full",
		Kind:    "individual",
		Name: &contacts.Name{
			Full: "Ada Lovelace",
			Components: []contacts.NameComponent{
				{Kind: "given", Value: "Ada"},
				{Kind: "surname", Value: "Lovelace"},
				{Kind: "prefix", Value: "Hon."},
			},
		},
		Emails: map[string]contacts.EmailAddress{
			"e0": {Address: "ada@example.test", Contexts: map[string]bool{"work": true}, Pref: 1},
		},
		Phones: map[string]contacts.Phone{
			"p0": {
				Number:   "+44 20 7946 0958",
				Features: map[string]bool{"voice": true},
				Contexts: map[string]bool{"work": true},
			},
		},
		Addresses: map[string]contacts.Address{
			"a0": {
				Components: []contacts.AddressComponent{
					{Kind: "name", Value: "10 Downing Street"},
					{Kind: "city", Value: "London"},
					{Kind: "postcode", Value: "SW1A 2AA"},
					{Kind: "country", Value: "United Kingdom"},
				},
				CountryCode: "GB",
				Contexts:    map[string]bool{"work": true},
			},
		},
		Organizations: map[string]contacts.Organization{
			"o0": {Name: "Analytical Engine Co.", Units: []string{"Research"}},
		},
		Titles: map[string]contacts.Title{
			"t0": {Name: "Mathematician", Kind: "title"},
			"r0": {Name: "Fellow", Kind: "role"},
		},
	}

	res, err := contacts.GenerateVCard(c, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	vcard := string(res.VCard)

	assertVCardContains(t, vcard, "FN:Ada Lovelace")
	assertVCardContains(t, vcard, "N:Lovelace;Ada;;Hon.;")
	assertVCardContains(t, vcard, "ada@example.test")
	assertVCardContains(t, vcard, "TYPE=work")
	assertVCardContains(t, vcard, "PREF=1")
	assertVCardContains(t, vcard, "+44 20 7946 0958")
	assertVCardContains(t, vcard, "10 Downing Street")
	assertVCardContains(t, vcard, "CC=GB")
	assertVCardContains(t, vcard, "ORG:Analytical Engine Co.;Research")
	assertVCardContains(t, vcard, "TITLE:Mathematician")
	assertVCardContains(t, vcard, "ROLE:Fellow")
	assertCRLFLineEndings(t, res.VCard)
}

func TestVCard_GenerateLineFolding(t *testing.T) {
	long := strings.Repeat("x", 200)
	c := cardWithNote(long)
	res, err := contacts.GenerateVCard(c, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	for _, line := range strings.Split(string(res.VCard), "\r\n") {
		if len(line) > 75 {
			preview := line
			if len(preview) > 40 {
				preview = preview[:40] + "..."
			}
			t.Errorf("line exceeds 75 octets (%d): %q", len(line), preview)
		}
	}
}

func TestVCard_GenerateUnrepresentable(t *testing.T) {
	c := &contacts.Card{Version: "1.0", UID: "urn:uuid:unr"}
	c.RawJSON = map[string]json.RawMessage{
		"keywords": []byte(`{"k1":{"value":"coding"}}`),
	}
	res, err := contacts.GenerateVCard(c, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	found := false
	for _, u := range res.Unrepresentable {
		if u.Type == "keywords" {
			found = true
		}
	}
	if !found {
		t.Error("keywords not reported as unrepresentable")
	}
}

func TestVCard_GenerateXPropRoundTrip(t *testing.T) {
	c := &contacts.Card{Version: "1.0", UID: "urn:uuid:xp"}
	c.Name = &contacts.Name{Full: "X"}
	c.RawJSON = map[string]json.RawMessage{
		"vcard:x-custom": []byte(`"hello world"`),
	}
	res, err := contacts.GenerateVCard(c, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	if !strings.Contains(string(res.VCard), "X-CUSTOM:hello world") {
		t.Errorf("X-CUSTOM not emitted; vcard:\n%s", res.VCard)
	}
}

func TestVCard_GeneratePhoto_FetchFn(t *testing.T) {
	c := &contacts.Card{Version: "1.0", UID: "urn:uuid:ph"}
	c.Name = &contacts.Name{Full: "Photo"}
	c.RawJSON = map[string]json.RawMessage{
		"media": vcardMustMarshal(map[string]interface{}{
			"photo/0": map[string]interface{}{
				"@type":     "MediaResource",
				"kind":      "photo",
				"blobId":    "blob-42",
				"mediaType": "image/png",
			},
		}),
	}
	fetchCalled := false
	fetch := contacts.PhotoFetchFn(func(blobId string) (string, []byte, error) {
		fetchCalled = true
		if blobId != "blob-42" {
			t.Errorf("fetchFn blobId = %q, want blob-42", blobId)
		}
		return "image/png", []byte("FAKEIMGDATA"), nil
	})
	res, err := contacts.GenerateVCard(c, fetch)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	if !fetchCalled {
		t.Error("PhotoFetchFn was not called")
	}
	if !strings.Contains(string(res.VCard), "PHOTO:data:image/png;base64,") {
		t.Errorf("PHOTO line not found; vcard:\n%s", res.VCard)
	}
}

func TestVCard_GenerateNilCard(t *testing.T) {
	_, err := contacts.GenerateVCard(nil, nil)
	if err == nil {
		t.Error("want error for nil card, got nil")
	}
}

// ===== Round-trip tests (REQ-CTS-13) =====

// TestVCard_RoundTrip_Individual tests a fully-populated individual card.
func TestVCard_RoundTrip_Individual(t *testing.T) {
	original := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:rt-individual",
		Kind:    "individual",
		Name: &contacts.Name{
			Full: "Alice Smith",
			Components: []contacts.NameComponent{
				{Kind: "given", Value: "Alice"},
				{Kind: "surname", Value: "Smith"},
				{Kind: "prefix", Value: "Dr."},
			},
		},
		Emails: map[string]contacts.EmailAddress{
			"work": {Address: "alice.work@example.test", Contexts: map[string]bool{"work": true}, Pref: 1},
			"home": {Address: "alice.home@example.test", Contexts: map[string]bool{"private": true}},
		},
		Phones: map[string]contacts.Phone{
			"cell": {Number: "+1 555 0100", Features: map[string]bool{"cell": true, "voice": true}},
			"fax":  {Number: "+1 555 0101", Features: map[string]bool{"fax": true}},
		},
		Addresses: map[string]contacts.Address{
			"work": {
				Components: []contacts.AddressComponent{
					{Kind: "name", Value: "123 Main St"},
					{Kind: "city", Value: "Springfield"},
					{Kind: "region", Value: "IL"},
					{Kind: "postcode", Value: "62701"},
					{Kind: "country", Value: "USA"},
				},
				CountryCode: "US",
				Contexts:    map[string]bool{"work": true},
			},
		},
		Organizations: map[string]contacts.Organization{
			"org": {Name: "ACME Corp", Units: []string{"Engineering", "R&D"}},
		},
		Titles: map[string]contacts.Title{
			"t": {Name: "Senior Engineer", Kind: "title"},
		},
		RawJSON: map[string]json.RawMessage{
			"nicknames": vcardMustMarshal(map[string]interface{}{
				"n0": map[string]interface{}{"@type": "Nickname", "name": "Ali"},
			}),
			"notes": vcardMustMarshal(map[string]interface{}{
				"note0": map[string]interface{}{"@type": "Note", "note": "Met at conference 2024."},
			}),
			"links": vcardMustMarshal(map[string]interface{}{
				"url0": map[string]interface{}{"@type": "Link", "kind": "uri", "uri": "https://alice.example.test"},
			}),
			"anniversaries": vcardMustMarshal(map[string]interface{}{
				"bday": map[string]interface{}{
					"@type": "Anniversary",
					"kind":  "birth",
					"date":  map[string]interface{}{"@type": "PartialDate", "year": float64(1990), "month": float64(5), "day": float64(15)},
				},
			}),
		},
	}

	roundTripped := roundTrip(t, original)
	assertRoundTripEquivalent(t, original, roundTripped)
}

// TestVCard_RoundTrip_Group tests a group card.
func TestVCard_RoundTrip_Group(t *testing.T) {
	original := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:rt-group",
		Kind:    "group",
		Name:    &contacts.Name{Full: "Engineering Team"},
	}

	roundTripped := roundTrip(t, original)
	if roundTripped.Kind != "group" {
		t.Errorf("Kind = %q, want group", roundTripped.Kind)
	}
	name := "<nil>"
	if roundTripped.Name != nil {
		name = roundTripped.Name.Full
	}
	if name != "Engineering Team" {
		t.Errorf("Name.Full = %q, want Engineering Team", name)
	}
}

// TestVCard_RoundTrip_MinimalName tests a name-only card.
func TestVCard_RoundTrip_MinimalName(t *testing.T) {
	original := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:rt-min",
		Name:    &contacts.Name{Full: "Zed"},
	}

	roundTripped := roundTrip(t, original)
	name := "<nil>"
	if roundTripped.Name != nil {
		name = roundTripped.Name.Full
	}
	if name != "Zed" {
		t.Errorf("Name.Full = %q, want Zed", name)
	}
}

// TestVCard_RoundTrip_Unicode tests a card with Unicode content.
func TestVCard_RoundTrip_Unicode(t *testing.T) {
	original := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:rt-uni",
		Name: &contacts.Name{
			Full: "李明",
			Components: []contacts.NameComponent{
				{Kind: "given", Value: "明"},
				{Kind: "surname", Value: "李"},
			},
		},
		Emails: map[string]contacts.EmailAddress{
			"e": {Address: "liming@例子.测试"},
		},
		Organizations: map[string]contacts.Organization{
			"o": {Name: "Café & Croissant; Bakery"},
		},
	}

	roundTripped := roundTrip(t, original)
	name := "<nil>"
	if roundTripped.Name != nil {
		name = roundTripped.Name.Full
	}
	if name != "李明" {
		t.Errorf("Name.Full = %q, want 李明", name)
	}
	assertEmailSetContains(t, roundTripped, "liming@例子.测试")
	assertOrgNameExists(t, roundTripped, "Café & Croissant; Bakery")
}

// TestVCard_RoundTrip_Escaping tests round-trip fidelity for vCard
// escape sequences: backslash, comma, semicolon, newline.
func TestVCard_RoundTrip_Escaping(t *testing.T) {
	original := &contacts.Card{
		Version: "1.0",
		UID:     "urn:uuid:rt-esc",
		Name:    &contacts.Name{Full: `Back\slash, Comma; Semicolon`},
		Organizations: map[string]contacts.Organization{
			"o": {Name: `Org\With;Special,Chars`},
		},
		RawJSON: map[string]json.RawMessage{
			"notes": vcardMustMarshal(map[string]interface{}{
				"n0": map[string]interface{}{
					"@type": "Note",
					"note":  "Line1\nLine2\nLine3",
				},
			}),
		},
	}

	roundTripped := roundTrip(t, original)
	if got := roundTripped.Name.Full; got != original.Name.Full {
		t.Errorf("Name.Full = %q, want %q", got, original.Name.Full)
	}
	assertOrgNameExists(t, roundTripped, `Org\With;Special,Chars`)
	assertRawJSONHasNote(t, roundTripped, "Line1\nLine2\nLine3")
}

// ExampleParseVCards demonstrates parsing a minimal vCard.
func ExampleParseVCards() {
	vcf := []byte("BEGIN:VCARD\r\nVERSION:4.0\r\nFN:Alice\r\nUID:urn:uuid:1\r\nEND:VCARD\r\n")
	results := contacts.ParseVCards(vcf, nil)
	if len(results) == 1 && results[0].Error == nil {
		fmt.Println(results[0].Card.Name.Full)
	}
	// Output: Alice
}

// ===== Helpers =====

func roundTrip(t *testing.T, src *contacts.Card) *contacts.Card {
	t.Helper()
	res, err := contacts.GenerateVCard(src, nil)
	if err != nil {
		t.Fatalf("GenerateVCard: %v", err)
	}
	results := contacts.ParseVCards(res.VCard, nil)
	if len(results) != 1 {
		t.Fatalf("ParseVCards: want 1, got %d", len(results))
	}
	if results[0].Error != nil {
		t.Fatalf("ParseVCards error: %v\nvCard:\n%s", results[0].Error, res.VCard)
	}
	return results[0].Card
}

func assertRoundTripEquivalent(t *testing.T, orig, rt *contacts.Card) {
	t.Helper()

	if orig.UID != rt.UID {
		t.Errorf("UID: orig=%q rt=%q", orig.UID, rt.UID)
	}
	if orig.Kind != rt.Kind {
		t.Errorf("Kind: orig=%q rt=%q", orig.Kind, rt.Kind)
	}

	if orig.Name != nil {
		if rt.Name == nil {
			t.Fatal("Name nil after round-trip")
		}
		if orig.Name.Full != "" && orig.Name.Full != rt.Name.Full {
			t.Errorf("Name.Full: orig=%q rt=%q", orig.Name.Full, rt.Name.Full)
		}
		for _, oc := range orig.Name.Components {
			found := false
			for _, rc := range rt.Name.Components {
				if rc.Kind == oc.Kind && rc.Value == oc.Value {
					found = true
					break
				}
			}
			if !found {
				t.Errorf("Name component {%s %q} missing after round-trip", oc.Kind, oc.Value)
			}
		}
	}

	for addr := range emailAddressSet(orig) {
		if !emailAddressSet(rt)[addr] {
			t.Errorf("email %q missing after round-trip", addr)
		}
	}
	for num := range phoneNumberSet(orig) {
		if !phoneNumberSet(rt)[num] {
			t.Errorf("phone %q missing after round-trip", num)
		}
	}
	for name := range orgNameSet(orig) {
		if !orgNameSet(rt)[name] {
			t.Errorf("org %q missing after round-trip", name)
		}
	}
	for name := range titleNameSet(orig) {
		if !titleNameSet(rt)[name] {
			t.Errorf("title %q missing after round-trip", name)
		}
	}
	for name := range rawJSONNicknameSet(orig) {
		if !rawJSONNicknameSet(rt)[name] {
			t.Errorf("nickname %q missing after round-trip", name)
		}
	}
	for text := range rawJSONNoteSet(orig) {
		if !rawJSONNoteSet(rt)[text] {
			t.Errorf("note %q missing after round-trip", text)
		}
	}
	for u := range rawJSONURLSet(orig) {
		if !rawJSONURLSet(rt)[u] {
			t.Errorf("url %q missing after round-trip", u)
		}
	}

	origBday := rawJSONBirthday(orig)
	rtBday := rawJSONBirthday(rt)
	if origBday != "" && origBday != rtBday {
		t.Errorf("birthday: orig=%q rt=%q", origBday, rtBday)
	}
}

// ===== assertion helpers =====

func assertVCardContains(t *testing.T, vcard, want string) {
	t.Helper()
	if !strings.Contains(vcard, want) {
		t.Errorf("vcard does not contain %q\nvcard:\n%s", want, vcard)
	}
}

func assertCRLFLineEndings(t *testing.T, b []byte) {
	t.Helper()
	s := string(b)
	for i := range s {
		if s[i] == '\n' && i > 0 && s[i-1] != '\r' {
			t.Errorf("bare LF at byte %d (no preceding CR)", i)
			return
		}
	}
}

func assertNameComponent(t *testing.T, c *contacts.Card, kind, value string) {
	t.Helper()
	if c.Name == nil {
		t.Fatalf("Name is nil, cannot check component %s=%q", kind, value)
	}
	for _, comp := range c.Name.Components {
		if comp.Kind == kind && comp.Value == value {
			return
		}
	}
	t.Errorf("Name component {%s %q} not found; components: %v", kind, value, c.Name.Components)
}

func assertAddrComponent(t *testing.T, a contacts.Address, kind, value string) {
	t.Helper()
	for _, comp := range a.Components {
		if comp.Kind == kind && comp.Value == value {
			return
		}
	}
	t.Errorf("Address component {%s %q} not found; components: %v", kind, value, a.Components)
}

func assertEmailExists(t *testing.T, c *contacts.Card, addr string, work bool) {
	t.Helper()
	for _, e := range c.Emails {
		if e.Address == addr {
			if work && !e.Contexts["work"] {
				t.Errorf("email %q: want work context, got %v", addr, e.Contexts)
			}
			if !work && !e.Contexts["private"] {
				t.Errorf("email %q: want private context, got %v", addr, e.Contexts)
			}
			return
		}
	}
	t.Errorf("email %q not found in card", addr)
}

func assertPrimaryEmail(t *testing.T, c *contacts.Card, want string) {
	t.Helper()
	if got := c.PrimaryEmail(); got != want {
		t.Errorf("PrimaryEmail = %q, want %q", got, want)
	}
}

func assertPhoneFeature(t *testing.T, c *contacts.Card, number, feature string) {
	t.Helper()
	for _, p := range c.Phones {
		if p.Number == number {
			if !p.Features[feature] {
				t.Errorf("phone %q: feature %q not set; features: %v", number, feature, p.Features)
			}
			return
		}
	}
	t.Errorf("phone %q not found", number)
}

func assertTitleKind(t *testing.T, c *contacts.Card, name, kind string) {
	t.Helper()
	for _, ti := range c.Titles {
		if ti.Name == name {
			if ti.Kind != kind {
				t.Errorf("title %q: kind = %q, want %q", name, ti.Kind, kind)
			}
			return
		}
	}
	t.Errorf("title %q not found", name)
}

func assertRawJSONHasNickname(t *testing.T, c *contacts.Card, name string) {
	t.Helper()
	raw, ok := c.RawJSON["nicknames"]
	if !ok {
		t.Fatalf("no nicknames in RawJSON, want %q", name)
	}
	var nicks map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &nicks); err != nil {
		t.Fatalf("unmarshal nicknames: %v", err)
	}
	for _, n := range nicks {
		if v, _ := n["name"].(string); v == name {
			return
		}
	}
	t.Errorf("nickname %q not found; nicks: %v", name, nicks)
}

func assertRawJSONHasNote(t *testing.T, c *contacts.Card, note string) {
	t.Helper()
	raw, ok := c.RawJSON["notes"]
	if !ok {
		t.Fatalf("no notes in RawJSON, want %q", note)
	}
	var notes map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &notes); err != nil {
		t.Fatalf("unmarshal notes: %v", err)
	}
	for _, n := range notes {
		if v, _ := n["note"].(string); v == note {
			return
		}
	}
	t.Errorf("note %q not found; notes: %v", note, notes)
}

func assertRawJSONHasURL(t *testing.T, c *contacts.Card, u string) {
	t.Helper()
	raw, ok := c.RawJSON["links"]
	if !ok {
		t.Fatalf("no links in RawJSON, want %q", u)
	}
	var links map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &links); err != nil {
		t.Fatalf("unmarshal links: %v", err)
	}
	for _, l := range links {
		if v, _ := l["uri"].(string); v == u {
			return
		}
	}
	t.Errorf("url %q not found; links: %v", u, links)
}

func assertRawJSONHasBirthday(t *testing.T, c *contacts.Card, year, month, day int) {
	t.Helper()
	raw, ok := c.RawJSON["anniversaries"]
	if !ok {
		t.Fatalf("no anniversaries in RawJSON")
	}
	var anns map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &anns); err != nil {
		t.Fatalf("unmarshal anniversaries: %v", err)
	}
	for _, a := range anns {
		if k, _ := a["kind"].(string); k != "birth" {
			continue
		}
		d, _ := a["date"].(map[string]interface{})
		if d == nil {
			continue
		}
		y, _ := d["year"].(float64)
		m, _ := d["month"].(float64)
		dy, _ := d["day"].(float64)
		if int(y) == year && int(m) == month && int(dy) == day {
			return
		}
	}
	t.Errorf("birthday %04d-%02d-%02d not found", year, month, day)
}

func assertRawJSONHasAnniversary(t *testing.T, c *contacts.Card, year, month, day int) {
	t.Helper()
	raw, ok := c.RawJSON["anniversaries"]
	if !ok {
		t.Fatalf("no anniversaries in RawJSON")
	}
	var anns map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &anns); err != nil {
		t.Fatalf("unmarshal anniversaries: %v", err)
	}
	for _, a := range anns {
		if k, _ := a["kind"].(string); k == "birth" {
			continue
		}
		d, _ := a["date"].(map[string]interface{})
		if d == nil {
			continue
		}
		y, _ := d["year"].(float64)
		m, _ := d["month"].(float64)
		dy, _ := d["day"].(float64)
		if (year == 0 || int(y) == year) && int(m) == month && int(dy) == day {
			return
		}
	}
	t.Errorf("anniversary year=%d month=%d day=%d not found", year, month, day)
}

func assertEmailSetContains(t *testing.T, c *contacts.Card, addr string) {
	t.Helper()
	for _, e := range c.Emails {
		if e.Address == addr {
			return
		}
	}
	t.Errorf("email %q not found", addr)
}

func assertOrgNameExists(t *testing.T, c *contacts.Card, name string) {
	t.Helper()
	for _, o := range c.Organizations {
		if o.Name == name {
			return
		}
	}
	t.Errorf("org %q not found", name)
}

// ===== set helpers for round-trip comparison =====

func emailAddressSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	for _, e := range c.Emails {
		m[e.Address] = true
	}
	return m
}

func phoneNumberSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	for _, p := range c.Phones {
		m[p.Number] = true
	}
	return m
}

func orgNameSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	for _, o := range c.Organizations {
		m[o.Name] = true
	}
	return m
}

func titleNameSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	for _, ti := range c.Titles {
		m[ti.Name] = true
	}
	return m
}

func rawJSONNicknameSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	if c.RawJSON == nil {
		return m
	}
	raw, ok := c.RawJSON["nicknames"]
	if !ok {
		return m
	}
	var nicks map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &nicks); err != nil {
		return m
	}
	for _, n := range nicks {
		if v, _ := n["name"].(string); v != "" {
			m[v] = true
		}
	}
	return m
}

func rawJSONNoteSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	if c.RawJSON == nil {
		return m
	}
	raw, ok := c.RawJSON["notes"]
	if !ok {
		return m
	}
	var notes map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &notes); err != nil {
		return m
	}
	for _, n := range notes {
		if v, _ := n["note"].(string); v != "" {
			m[v] = true
		}
	}
	return m
}

func rawJSONURLSet(c *contacts.Card) map[string]bool {
	m := make(map[string]bool)
	if c.RawJSON == nil {
		return m
	}
	raw, ok := c.RawJSON["links"]
	if !ok {
		return m
	}
	var links map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &links); err != nil {
		return m
	}
	for _, l := range links {
		if v, _ := l["uri"].(string); v != "" {
			m[v] = true
		}
	}
	return m
}

func rawJSONBirthday(c *contacts.Card) string {
	if c.RawJSON == nil {
		return ""
	}
	raw, ok := c.RawJSON["anniversaries"]
	if !ok {
		return ""
	}
	var anns map[string]map[string]interface{}
	if err := json.Unmarshal(raw, &anns); err != nil {
		return ""
	}
	for _, a := range anns {
		if k, _ := a["kind"].(string); k == "birth" {
			d, _ := a["date"].(map[string]interface{})
			if d == nil {
				continue
			}
			y, _ := d["year"].(float64)
			m, _ := d["month"].(float64)
			dy, _ := d["day"].(float64)
			return fmt.Sprintf("%04d-%02d-%02d", int(y), int(m), int(dy))
		}
	}
	return ""
}

func cardWithNote(note string) *contacts.Card {
	c := &contacts.Card{Version: "1.0", UID: "urn:uuid:note"}
	c.Name = &contacts.Name{Full: "N"}
	c.RawJSON = map[string]json.RawMessage{
		"notes": vcardMustMarshal(map[string]interface{}{
			"n0": map[string]interface{}{"@type": "Note", "note": note},
		}),
	}
	return c
}

func vcardMustMarshal(v interface{}) json.RawMessage {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}
