package admin

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"runtime/debug"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

func newDiagCollectCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "collect",
		Short: "produce a support bundle (config, logs, queue stats, plugin status, cert table, versions)",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			g := globals(cmd.Context())
			outDir, _ := cmd.Flags().GetString("out")
			if outDir == "" {
				outDir = fmt.Sprintf("./herold-collect-%s", time.Now().UTC().Format("20060102-150405"))
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return fmt.Errorf("collect: create %s: %w", outDir, err)
			}
			// 1. Server config (with secrets redacted).
			if g.configPath != "" {
				raw, err := os.ReadFile(g.configPath)
				if err != nil {
					writeLine(cmd.OutOrStdout(), g, fmt.Sprintf("collect: warn: read config %s: %v", g.configPath, err))
				} else {
					redacted := redactSecretsTOML(raw)
					if err := os.WriteFile(filepath.Join(outDir, "system.toml"), redacted, 0o600); err != nil {
						return fmt.Errorf("collect: write system.toml: %w", err)
					}
				}
			}

			// 2. Software versions.
			versions := map[string]any{
				"go":        runtime.Version(),
				"goos":      runtime.GOOS,
				"goarch":    runtime.GOARCH,
				"collected": time.Now().UTC().Format(time.RFC3339),
			}
			if bi, ok := debug.ReadBuildInfo(); ok {
				versions["module"] = bi.Main.Path
				versions["version"] = bi.Main.Version
			}
			if err := writeJSONFile(filepath.Join(outDir, "versions.json"), versions); err != nil {
				return err
			}

			// 3. REST-driven artifacts. Best-effort: a missing endpoint or
			// auth failure logs and continues.
			client, clientErr := clientFromGlobals(g)
			if clientErr != nil {
				writeLine(cmd.OutOrStdout(), g, fmt.Sprintf("collect: warn: %v (skipping REST-driven artifacts)", clientErr))
			} else {
				type artifact struct {
					path  string
					url   string
					label string
				}
				artifacts := []artifact{
					{filepath.Join(outDir, "queue_stats.json"), "/api/v1/queue/stats", "queue stats"},
					{filepath.Join(outDir, "certs.json"), "/api/v1/certs", "cert table"},
					{filepath.Join(outDir, "audit_log.json"), "/api/v1/audit?limit=1000", "audit log"},
					{filepath.Join(outDir, "principals.json"), "/api/v1/principals?limit=1000", "principals"},
					{filepath.Join(outDir, "domains.json"), "/api/v1/domains", "domains"},
					{filepath.Join(outDir, "server_status.json"), "/api/v1/server/status", "server status"},
				}
				for _, a := range artifacts {
					var got any
					if err := client.do(cmd.Context(), "GET", a.url, nil, &got); err != nil {
						writeLine(cmd.OutOrStdout(), g, fmt.Sprintf("collect: warn: fetch %s (%s): %v", a.label, a.url, err))
						continue
					}
					if err := writeJSONFile(a.path, got); err != nil {
						return err
					}
				}
			}

			// 4. Recent log lines (best-effort): scan the first --log file
			// from the system config (if obtainable) or skip when the path
			// is unknown. Log discovery is conservative — we look for a
			// HEROLD_LOG_FILE environment variable; absent, we skip.
			if logPath := os.Getenv("HEROLD_LOG_FILE"); logPath != "" {
				if err := copyTail(logPath, filepath.Join(outDir, "log.tail.txt"), 1000); err != nil {
					writeLine(cmd.OutOrStdout(), g, fmt.Sprintf("collect: warn: tail %s: %v", logPath, err))
				}
			}

			// 5. README so consumers of the bundle know what's inside.
			readme := strings.Join([]string{
				"# herold support bundle",
				"",
				fmt.Sprintf("Generated by `herold diag collect` at %s.", time.Now().UTC().Format(time.RFC3339)),
				"",
				"Contents:",
				"- system.toml      — system config with secrets redacted",
				"- versions.json    — Go runtime + build info",
				"- queue_stats.json — outbound queue counts by state",
				"- certs.json       — ACME-managed certificates",
				"- audit_log.json   — recent audit-log entries (up to 1000)",
				"- principals.json  — principals (up to 1000)",
				"- domains.json     — local domains",
				"- server_status.json — admin /server/status snapshot",
				"- log.tail.txt     — last 1000 lines of $HEROLD_LOG_FILE (if set)",
				"",
			}, "\n")
			if err := os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readme), 0o644); err != nil {
				return fmt.Errorf("collect: write README: %w", err)
			}
			writeLine(cmd.OutOrStdout(), g, "support bundle written to "+outDir)
			return nil
		},
	}
	cmd.Flags().String("out", "", "output directory (default ./herold-collect-<timestamp>)")
	return cmd
}

func writeJSONFile(path string, body any) error {
	raw, err := json.MarshalIndent(body, "", "  ")
	if err != nil {
		return fmt.Errorf("collect: marshal %s: %w", path, err)
	}
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		return fmt.Errorf("collect: write %s: %w", path, err)
	}
	return nil
}

// secretLineRE matches TOML lines whose key suggests it carries
// authentication material. The redactor replaces the value with
// "<redacted>" while preserving the key + comment shape. The key
// portion is anchored: it must either be one of the known-bad tokens
// or end with an underscore + token. So `secret`, `client_secret`,
// `api_key`, `hmac_secret_b64` redact; `nonsecret`, `presence` do not.
var secretLineRE = regexp.MustCompile(`(?im)^(\s*((?:[a-zA-Z0-9]+_)?(?:secret|password|token|api_key|client_secret|hmac|key_pem|private_key|access_key|refresh_token)(?:_[a-zA-Z0-9]+)?)\s*=\s*)("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|[^#\n]*)(\s*(#.*)?)$`)

// redactSecretsTOML replaces inline secret values with "<redacted>" so a
// shared bundle does not leak credentials. The redactor is intentionally
// conservative — it covers the common key names we use across system.toml
// and never rewrites anything outside of "key = value" lines, so a key
// table reference or env-only secret survives intact.
func redactSecretsTOML(raw []byte) []byte {
	return secretLineRE.ReplaceAll(raw, []byte(`${1}"<redacted>"${4}`))
}

// copyTail reads at most lastN lines from src and writes them to dst. The
// implementation reads the whole file into memory (1000 lines is small)
// rather than seeking backwards; operators with massive log files can
// pre-tail outside this command.
func copyTail(src, dst string, lastN int) error {
	raw, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	lines := strings.Split(string(raw), "\n")
	if len(lines) > lastN {
		lines = lines[len(lines)-lastN:]
	}
	return os.WriteFile(dst, []byte(strings.Join(lines, "\n")), 0o600)
}
