package store

import "time"

// SRSSecretID identifies one row in the srs_secrets table.
type SRSSecretID uint64

// SRSSecret is one keyed-MAC secret used by internal/srs to sign and
// verify SRS (Sender Rewriting Scheme) return-path addresses (issue
// #204). Rotation is additive: a new secret becomes the signing
// secret (the row with the highest ID); older rows are retained and
// still validated against on decode, so an in-flight SRS address
// keeps working across a rotation until it ages out on its own SRS0
// timestamp or the operator explicitly prunes the row.
type SRSSecret struct {
	// ID is the stable primary key. Rows are consulted in ascending
	// ID order; the highest ID is the current signing secret.
	ID SRSSecretID
	// Secret is opaque key material (32 random bytes, generated by
	// internal/srs on first use). Stored in plaintext, matching the
	// existing DKIMKey.PrivateKeyPEM precedent: the store itself is
	// the trust boundary, not an additional encryption layer.
	Secret []byte
	// CreatedAt is the insert instant.
	CreatedAt time.Time
}
