package store

import "time"

// -- Sub-account promotion (issue #227, REQ-SUBACCT-09, REQ-IMAP-IMP-106/107) --
//
// A sub-account (store.PrincipalKindSubAccount) already exists as a
// first-class principal kind (types.go). This file adds the bookkeeping
// for *promoting* an existing Identity into one: SeparateIdentity creates
// the sub-principal and kicks off a resumable sweep that reparents the
// mail the Identity's IMAP-import account already pulled in; a
// SubAccountMigration row tracks that sweep's status across a restart.

// SubAccountMigrationStatus is the lifecycle state of a SubAccountMigration
// row.
type SubAccountMigrationStatus string

const (
	// SubAccountMigrationStatusPending means SeparateIdentity has created
	// the sub-principal and the row, but RunSubAccountMigration has not
	// yet started (or was never invoked after a crash before it began).
	SubAccountMigrationStatusPending SubAccountMigrationStatus = "pending"
	// SubAccountMigrationStatusRunning means a sweep is (or was, before a
	// crash) in progress. ListPendingSubAccountMigrations returns rows in
	// this state too, so boot-time resume picks them back up.
	SubAccountMigrationStatusRunning SubAccountMigrationStatus = "running"
	// SubAccountMigrationStatusDone means every message tracked by the
	// separated Identity's import account has been reparented or copied;
	// re-running RunSubAccountMigration on a done row is a no-op success.
	SubAccountMigrationStatusDone SubAccountMigrationStatus = "done"
)

// SubAccountMigration is one row in the subaccount_migrations table: the
// record of separating identityID (owned by ParentPrincipalID) into
// SubPrincipalID, and the resumable sweep's progress.
type SubAccountMigration struct {
	// ID is the opaque string primary key (32-hex, generated by the
	// store on create), mirroring IMAPImportAccount.ID.
	ID string
	// ParentPrincipalID is the individual principal the Identity used to
	// belong to.
	ParentPrincipalID PrincipalID
	// SubPrincipalID is the newly-created sub-principal
	// (PrincipalKindSubAccount) the Identity now belongs to.
	SubPrincipalID PrincipalID
	// IdentityID is the JMAP Identity (jmap_identities.id) being
	// separated.
	IdentityID string
	// Status is the sweep's lifecycle state.
	Status SubAccountMigrationStatus
	// MessagesTotal is a best-effort count of messages tracked by the
	// Identity's import account(s) at sweep start, for progress display.
	// Not authoritative for completion -- RunSubAccountMigration
	// re-derives its work list from imapimport_message_state on every
	// call rather than trusting this snapshot.
	MessagesTotal int64
	// MessagesMoved counts messages whose only claim was this Identity's
	// import channel: reparented in place (REQ-IMAP-IMP-106 move case).
	MessagesMoved int64
	// MessagesCopied counts messages also claimed by another channel
	// (native delivery, a second import account): copied into the
	// sub-account, left in place in the parent (REQ-IMAP-IMP-103/106
	// dedup-safe copy case).
	MessagesCopied int64
	// LastError is the most recent sweep-step error, or empty. Retained
	// across a crash for operator visibility; cleared on the next
	// successful RunSubAccountMigration call.
	LastError string
	// CreatedAt / UpdatedAt are the row lifecycle timestamps.
	CreatedAt time.Time
	UpdatedAt time.Time
}

// CopyImportedMessageRequest is the input to
// Metadata.CopyImportedMessageToSubAccount: the dedup-safe copy step of a
// sub-account migration sweep (REQ-IMAP-IMP-103/106) for one message that
// is also claimed by a channel other than the import account being
// separated.
type CopyImportedMessageRequest struct {
	// AccountID is the imapimport_account.id whose message_state rows are
	// being swept. Used to locate the durable copied_message_id marker.
	AccountID string
	// SourceMessageID is the existing message (still owned by the parent
	// principal) being copied.
	SourceMessageID MessageID
	// NewMessage carries the fields for the sub-account's copy:
	// PrincipalID MUST be the sub-principal; Blob/Size/Envelope/etc. are
	// copied verbatim from the source message by the caller.
	NewMessage Message
	// Targets names the sub-account mailbox membership(s) to create for
	// the copy (mirroring the source message's memberships that belong
	// to this import account, mapped into the sub-account's tree).
	Targets []MessageMailbox
}

// CopyImportedMessageResult is the output of
// Metadata.CopyImportedMessageToSubAccount.
type CopyImportedMessageResult struct {
	// MessageID is the sub-account's copy of the message: freshly
	// inserted, or the pre-existing copy from an earlier, interrupted
	// run (AlreadyDone == true).
	MessageID MessageID
	// AlreadyDone is true when a prior run already completed this copy
	// (the durable marker was already set); no new message row or blob
	// reference was created by this call.
	AlreadyDone bool
}
