#!/usr/bin/env bash
# scripts/dev-server.sh
#
# Persistent herold development server.
# Invoked by `make dev`. Starts the herold backend and the Vite suite
# SPA together in the foreground; Ctrl-C stops both cleanly.
#
# Unlike scripts/dev-instance.sh (ephemeral, agent-oriented), this
# script maintains a persistent state directory that survives restarts
# so the maintainer's test mail and other local state accumulate across
# sessions.
#
# Environment overrides:
#   HEROLD_DEV_DIR          state directory (default: <repo-root>/.dev/)
#   HEROLD_DEV_BACKEND_PORT public HTTP port (default: 8080)
#   HEROLD_DEV_VITE_PORT    Vite HMR port (default: 5173)
#   HEROLD_BIN              herold binary (default: <repo-root>/bin/herold)
#   HEROLD_SEED_PASSWORD    seed password (default: testpass123...)
#   HEROLD_SEED_DOMAIN      seed domain (default: example.local)
#
# Ports: the public HTTP listener binds HEROLD_DEV_BACKEND_PORT.
# Admin, IMAP, and SMTP listeners bind 127.0.0.1:0 (kernel-assigned);
# their resolved addresses appear in the startup banner.
#
# First run: provisions the self-signed TLS cert, bootstraps
# admin@<domain>, and seeds alice/filip/bob on <domain>.
# Subsequent runs: reuse the existing store without re-bootstrap or
# re-seed, so accumulated test state survives restarts.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HEROLD_BIN="${HEROLD_BIN:-$REPO_ROOT/bin/herold}"
DEV_DIR="${HEROLD_DEV_DIR:-$REPO_ROOT/.dev}"
BACKEND_PORT="${HEROLD_DEV_BACKEND_PORT:-8080}"
VITE_PORT="${HEROLD_DEV_VITE_PORT:-5173}"
SEED_PASSWORD="${HEROLD_SEED_PASSWORD:-testpass123...}"
SEED_DOMAIN="${HEROLD_SEED_DOMAIN:-example.local}"
READY_TIMEOUT="${HEROLD_READY_TIMEOUT:-30}"

SEED_PRINCIPALS=(
    "admin:admin"
    "alice:user"
    "filip:user"
    "bob:user"
)

# ── small utilities ──────────────────────────────────────────────────

die() { echo "dev-server: $*" >&2; exit 1; }
log() { echo "dev-server: $*" >&2; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

# wait_for_file PATH TIMEOUT_SECONDS -- polls until the file is non-empty.
wait_for_file() {
    local path="$1" deadline=$(( $(date +%s) + ${2:-30} ))
    while [ ! -s "$path" ]; do
        [ "$(date +%s)" -ge "$deadline" ] && return 1
        sleep 0.1
    done
    return 0
}

# wait_for_http URL TIMEOUT_SECONDS -- polls until the URL returns any HTTP status.
wait_for_http() {
    local url="$1" deadline=$(( $(date +%s) + ${2:-30} ))
    while ! curl -s -o /dev/null -w '%{http_code}' "$url" 2>/dev/null | grep -q '^[0-9][0-9][0-9]$'; do
        [ "$(date +%s)" -ge "$deadline" ] && return 1
        sleep 0.2
    done
    return 0
}

# read_port_from_report LISTENER_NAME -- extract the address field for
# a named listener from DEV_DIR/ports.toml.
read_port_from_report() {
    local name="$1"
    local report="$DEV_DIR/ports.toml"
    [ -s "$report" ] || { echo ""; return 1; }
    awk -v name="$name" '
        /^\[\[listener\]\]/ { in_block=1; cur_name=""; cur_addr=""; next }
        in_block && /^name *= */ { sub(/^name *= */, ""); gsub(/"/, ""); cur_name=$0 }
        in_block && /^address *= */ {
            sub(/^address *= */, ""); gsub(/"/, ""); cur_addr=$0
            if (cur_name == name) { print cur_addr; exit 0 }
        }
    ' "$report"
}

# kill_tree PID SIG -- send SIG to PID and all transitive descendants.
# pnpm -> node -> vite -> esbuild; SIGTERM to the root orphans children
# without the tree walk.
kill_tree() {
    local pid="$1" sig="${2:-TERM}"
    [ -n "$pid" ] || return 0
    local children
    children=$(pgrep -P "$pid" 2>/dev/null || true)
    for child in $children; do
        kill_tree "$child" "$sig"
    done
    kill -"$sig" "$pid" 2>/dev/null || true
}

# ── config generation ────────────────────────────────────────────────

write_system_toml() {
    local cert="$DEV_DIR/data/admin.crt"
    local key="$DEV_DIR/data/admin.key"
    cat > "$DEV_DIR/system.toml" <<EOF
# Generated by scripts/dev-server.sh. Persistent dev config.
# The public listener port is set from HEROLD_DEV_BACKEND_PORT;
# all other listeners bind :0 (kernel-assigned, reported in ports.toml).

[server]
hostname = "mail.$SEED_DOMAIN"
data_dir = "$DEV_DIR/data"
shutdown_grace = "1s"
port_report_file = "$DEV_DIR/ports.toml"

[server.admin_tls]
source = "file"
cert_file = "$cert"
key_file  = "$key"

[server.storage]
backend = "sqlite"

[server.storage.sqlite]
path = "$DEV_DIR/data/herold.sqlite"

[[listener]]
name = "smtp-relay"
address = "127.0.0.1:0"
protocol = "smtp"
tls = "none"

[[listener]]
name = "smtp-submission"
address = "127.0.0.1:0"
protocol = "smtp-submission"
tls = "starttls"
auth_required = true
cert_file = "$cert"
key_file  = "$key"

[[listener]]
name = "imap"
address = "127.0.0.1:0"
protocol = "imap"
tls = "starttls"
cert_file = "$cert"
key_file  = "$key"

[[listener]]
name = "public"
address = "127.0.0.1:$BACKEND_PORT"
protocol = "http"
kind = "public"
tls = "none"

[[listener]]
name = "admin"
address = "127.0.0.1:0"
protocol = "http"
kind = "admin"
tls = "none"

[server.suite]
enabled = true

[observability]
metrics_bind = "127.0.0.1:0"

[[log.sink]]
target = "stderr"
format = "console"
level  = "info"
activities = { deny = ["poll", "access"] }

[[log.sink]]
target = "herold.jsonl"
format = "json"
level  = "debug"
EOF
}

# ── seeding ──────────────────────────────────────────────────────────

seed_principals() {
    local admin_url="$1" api_key="$2"
    for spec in "${SEED_PRINCIPALS[@]}"; do
        local local_part="${spec%%:*}"
        [ "$local_part" = "admin" ] && continue
        log "creating principal $local_part@$SEED_DOMAIN"
        HEROLD_API_KEY="$api_key" "$HEROLD_BIN" principal create \
            "$local_part@$SEED_DOMAIN" \
            --password "$SEED_PASSWORD" \
            --server-url "$admin_url" \
            --system-config "$DEV_DIR/system.toml" \
            --quiet \
            >/dev/null 2>"$DEV_DIR/logs/principal-$local_part.err" \
            || { cat "$DEV_DIR/logs/principal-$local_part.err" >&2
                 die "principal create $local_part failed"; }
    done
}

# ── main ─────────────────────────────────────────────────────────────

require_cmd curl
[ -x "$HEROLD_BIN" ] || die "herold binary not found at $HEROLD_BIN; run 'make build-server' first"

mkdir -p "$DEV_DIR/data" "$DEV_DIR/logs"

# Remove stale port report from a previous run so we can poll for a fresh one.
rm -f "$DEV_DIR/ports.toml"

first_run=0
if [ ! -f "$DEV_DIR/data/herold.sqlite" ]; then
    first_run=1
    log "first run -- provisioning $DEV_DIR"
else
    log "resuming existing dev environment in $DEV_DIR"
fi

# Generate TLS cert once; guard prevents overwriting on subsequent runs.
if [ ! -f "$DEV_DIR/data/admin.crt" ]; then
    log "generating self-signed TLS cert"
    "$REPO_ROOT/scripts/make-self-signed-cert.sh" "$DEV_DIR/data" "mail.$SEED_DOMAIN" \
        >> "$DEV_DIR/logs/cert.log" 2>&1 \
        || die "cert generation failed; see $DEV_DIR/logs/cert.log"
fi

# Rewrite system.toml on every run so port changes take effect.
write_system_toml

if [ "$first_run" = "1" ]; then
    log "bootstrapping admin@$SEED_DOMAIN"
    "$HEROLD_BIN" bootstrap \
        --system-config "$DEV_DIR/system.toml" \
        --email "admin@$SEED_DOMAIN" \
        --password "$SEED_PASSWORD" \
        --save-credentials=false \
        > "$DEV_DIR/bootstrap.out" 2> "$DEV_DIR/bootstrap.err" \
        || die "bootstrap failed; see $DEV_DIR/bootstrap.err"
    api_key=$(awk -F': ' '/^[[:space:]]*api_key:/ { print $2; exit }' "$DEV_DIR/bootstrap.out")
    [ -n "$api_key" ] || die "bootstrap did not emit api_key; see $DEV_DIR/bootstrap.out"
    printf '%s\n' "$api_key" > "$DEV_DIR/api-key.txt"
    chmod 600 "$DEV_DIR/api-key.txt"
fi

# Start the herold backend. Output goes to the log file; the banner
# below tells the maintainer where to find it.
log "starting herold backend on 127.0.0.1:$BACKEND_PORT"
"$HEROLD_BIN" server start \
    --system-config "$DEV_DIR/system.toml" \
    >> "$DEV_DIR/logs/herold.log" 2>&1 &
herold_pid=$!

# Wait for the port report (written by herold once all listeners are bound).
if ! wait_for_file "$DEV_DIR/ports.toml" "$READY_TIMEOUT"; then
    kill "$herold_pid" 2>/dev/null || true
    die "herold did not write ports.toml within ${READY_TIMEOUT}s; see $DEV_DIR/logs/herold.log"
fi

admin_addr=$(read_port_from_report "admin")
[ -n "$admin_addr" ] || { kill "$herold_pid" 2>/dev/null || true
                           die "admin listener address not found in ports.toml"; }
admin_url="http://$admin_addr"
imap_addr=$(read_port_from_report "imap" || echo "127.0.0.1:?")
smtp_addr=$(read_port_from_report "smtp-relay" || echo "127.0.0.1:?")
smtp_sub_addr=$(read_port_from_report "smtp-submission" || echo "127.0.0.1:?")

# Wait for the public listener to accept connections.
backend_url="http://127.0.0.1:$BACKEND_PORT"
if ! wait_for_http "$backend_url/" "$READY_TIMEOUT"; then
    kill "$herold_pid" 2>/dev/null || true
    die "backend did not answer on $backend_url within ${READY_TIMEOUT}s; see $DEV_DIR/logs/herold.log"
fi

# Seed non-admin principals on first run only.
if [ "$first_run" = "1" ]; then
    api_key=$(cat "$DEV_DIR/api-key.txt")
    seed_principals "$admin_url" "$api_key"
fi

# Ensure the pnpm workspace is installed before starting Vite.
if [ ! -d "$REPO_ROOT/web/node_modules" ]; then
    log "installing pnpm workspace (no node_modules found)"
    ( cd "$REPO_ROOT/web" && pnpm install --frozen-lockfile ) \
        >> "$DEV_DIR/logs/pnpm-install.log" 2>&1 \
        || die "pnpm install failed; see $DEV_DIR/logs/pnpm-install.log"
fi

# Print the startup banner.
cat <<EOF

====================================================================
 herold dev
 Suite:        http://localhost:$VITE_PORT/
 Backend:      $backend_url
 Admin API:    $admin_url
 IMAP:         $imap_addr  (STARTTLS)
 SMTP relay:   $smtp_addr
 SMTP submit:  $smtp_sub_addr  (STARTTLS)
 Domain:       $SEED_DOMAIN
 Credentials:  admin@$SEED_DOMAIN  $SEED_PASSWORD
               alice@$SEED_DOMAIN  $SEED_PASSWORD
               filip@$SEED_DOMAIN  $SEED_PASSWORD
               bob@$SEED_DOMAIN    $SEED_PASSWORD
 State dir:    $DEV_DIR
 Backend log:  $DEV_DIR/logs/herold.log
 Press Ctrl-C to stop (state in $DEV_DIR persists).
====================================================================

EOF

# Cleanup trap -- shuts down both processes but preserves DEV_DIR.
vite_pid=""
cleanup() {
    log "shutting down"
    [ -n "$vite_pid" ] && kill_tree "$vite_pid" TERM
    kill_tree "$herold_pid" TERM
    sleep 1
    [ -n "$vite_pid" ] && kill_tree "$vite_pid" KILL
    kill_tree "$herold_pid" KILL
    log "stopped; state preserved in $DEV_DIR"
}
trap cleanup EXIT INT TERM

# Start Vite. Output goes directly to the terminal for live HMR feedback.
log "starting Vite on http://localhost:$VITE_PORT/ (HEROLD_URL=$backend_url)"
HEROLD_URL="$backend_url" \
    pnpm --dir "$REPO_ROOT/web/apps/suite" exec vite \
    --port "$VITE_PORT" --strictPort &
vite_pid=$!

# Block until either process exits; the EXIT trap cleans up the other.
wait "$herold_pid" "$vite_pid"
